version: "2"

services:
    app:
        image: nasajon/django:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - $PWD:/var/www/html
        env_file:
            - common.env

    postgres:
        image: postgres:11.4
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - $PWD/database/dump:/docker-entrypoint-initdb.d/
        environment:
            - "POSTGRES_DB=django_skeleton"
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=mysecretpassword"
